# -*- coding: utf-8 -*-
"""Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f6Ars_pH6P6upSQEd9EoZYNRR_RV1oks
"""

Number_1 = 0
Number_2 = 0
Number_1=input("give first number:")
Number_2=input("give second number:")
Operator=input("give operator:")
#if not number_1.isnumeric() or not number_2.isnumeric():
#    print("you can not give alphbets for numaric values")
#    exit ()
#else:
try:
    Number_1 = float(Number_1)
    Number_2 = float(Number_2)
except ValueError:
    print("Please enter numeric values only.")
    exit()

if Operator=="+":
           print(Number_1 + Number_2)
elif Operator=="-":
           print(Number_1 - Number_2)
elif Operator=="*":
           print(Number_1 * Number_2)
elif Operator=="/":
           if Number_2!=0:
             print(Number_1/Number_2)
           else:
             print("you can not divide a number by zero")
else:
           print("you have given wrong operator")

