# -*- coding: utf-8 -*-
"""word occurance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N-Vz6P8lIqyorUiZSbW9A2rKLJLGBAtW
"""

line = input("type a line to calculate word count :")
print(line)
dist={}
words=line.split()
for word in words:
    if word in dist:
        dist[word]=dist[word]+1
    else:
        dist[word]=1
print(dist)

print("kesa phir ")

